<Project Sdk="Remora.Resonite.Sdk/2.3.3">
  <PropertyGroup>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>DynamicVariablePowerTools</PackageId>
    <Title>Dynamic Variable Power Tools</Title>
    <Authors>Banane9</Authors>
    <Version>0.1.1-beta</Version>
    <Description>This MonkeyLoader mod for Resonite adds a variety of powerful functions to dynamic variables and their spaces.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ResoniteModdingGroup/DynamicVariablePowerTools</PackageProjectUrl>
    <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
    <PackageTags>mod; mods; monkeyloader; resonite; contacts</PackageTags>

    <MonkeyLoader_GamePacks_Resonite_Version>0.33.0</MonkeyLoader_GamePacks_Resonite_Version>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" />
    <None Include="Locale/*" Pack="true" PackagePath="content/Locale/" />

    <Compile Update="ContextMenu/DVMA.*.cs" DependentUpon="ContextMenu/DynamicVariableMemberActions.cs" />
  </ItemGroup>

  <ItemGroup>
    <ResoniteReference Include="Elements.Core" />
    <ResoniteReference Include="Elements.Quantity" />
    <ResoniteReference Include="FrooxEngine" />
    <ResoniteReference Include="ProtoFluxBindings" />
  </ItemGroup>
</Project>
